FROM gcc:14

RUN apt-get update && apt-get install -y cmake iproute2

WORKDIR /cserver
COPY . .
RUN mkdir build && cd build && cmake .. && make

COPY entrypoint.sh .
RUN chmod +x entrypoint.sh

ENTRYPOINT ["./entrypoint.sh", "./build/server"]
